version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-subman}
      POSTGRES_USER: ${DB_USER:-qwerty}
      POSTGRES_PASSWORD: ${DB_PASS:-qwerty}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SERVER_PORT: 7070
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-subman}
      DB_USER: ${DB_USER:-qwerty}
      DB_PASS: ${DB_PASS:-qwerty}
    ports:
      - "7070:7070"

    command: ["/app/server"]

volumes:
  pgdata: