definitions:
  common.Response:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  subscription.SubscriptionCreateDTO:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  subscription.SubscriptionUpdateDTO:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/subscriptions:
    get:
      consumes:
      - application/json
      description: Returns a list of all subscriptions by user-id
      parameters:
      - description: User ID
        in: query
        name: user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Get all user subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Creates a new subscription record
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subscription.SubscriptionCreateDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/common.Response'
      summary: Create subscription
      tags:
      - subscriptions
  /api/subscriptions/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a subscription by its ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Delete subscription
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Returns a subscription by its ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Updates an existing subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subscription.SubscriptionUpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Update subscription
      tags:
      - subscriptions
  /api/subscriptions/total-price:
    get:
      consumes:
      - application/json
      description: Calculates the total price of user subscriptions for a period
      parameters:
      - description: User ID
        in: query
        name: user-id
        required: true
        type: string
      - description: Service name
        in: query
        name: service-name
        type: string
      - description: Start date (MM-YYYY)
        in: query
        name: from
        type: string
      - description: End date (MM-YYYY)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Get total subscription price
      tags:
      - subscriptions
swagger: "2.0"
